enabled: false
replicaCount: 1

image:
  repository: harbor.poc.workisboring.com/mix/mix-backend
  tag: "latest"

imagePullSecrets: 
- name: regcred

service:
  targetPort: 8080

resources: 
  limits:
    cpu: 2.5
    memory: 512Mi
  requests:
    cpu: 1.5
    memory: 256Mi
